service: mysql-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "rds-db:connect"
          Resource: "arn:aws:rds-db:eu-west-1:632021086366:database:prx-0a0372dc152eb04a5/*"
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  vpc:
    securityGroupIds:
      - "sg-0471e61254a614c13"
    subnetIds:
      - "subnet-0e2a404afb9ca2b2d"
      - "subnet-06b799a86717fc266"
      - "subnet-04622113c9dc85a04"
resources:
  Resources:
functions:
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auction
    Environment:
      Variables:
        DB_HOST: !Ref DBEndpoint
        DB_USER: !Ref DBUsername
        DB_NAME: !Ref DBName
    Layers:
      - !Ref DependenciesLayer
    Policies:
        Version:  '2012-10-17'
        Statement:
          Effect: Allow
          Action:
            - rds-db:connect
          Resource:
            - !Sub "arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DBResourceId}/${DBUsername}"



